<?php

use Illuminate\Database\Seeder;

class CoursecodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('coursecodes')->insert([
        	['id' => 1, 'name' => 'CSC 101'],
        	['id' => 2, 'name' => 'CMS 107'],
        	['id' => 3, 'name' => 'ILT 101'],
            ['id' => 4, 'name' => 'MAT 101'],
            ['id' => 5, 'name' => 'PHY 101'],
            ['id' => 6, 'name' => 'CSC 102'],
            ['id' => 7, 'name' => 'CMS 108'],
            ['id' => 8, 'name' => 'MAT 102'],
            ['id' => 9, 'name' => 'PHY 102'],
            ['id' => 10, 'name' => 'CSC 201'],
            ['id' => 11, 'name' => 'CSC 203'],
            ['id' => 12, 'name' => 'MAT 201'],
            ['id' => 13, 'name' => 'PHY 201'],
            ['id' => 14, 'name' => 'PHY 203'],
            ['id' => 15, 'name' => 'CSC 202'],
            ['id' => 16, 'name' => 'CSC 204'],
            ['id' => 17, 'name' => 'MAT 202'],
            ['id' => 18, 'name' => 'MAT 204'],
            ['id' => 19, 'name' => 'PHY 202'],
            ['id' => 20, 'name' => 'PHY 204'],
            ['id' => 21, 'name' => 'CSC 301'],
            ['id' => 22, 'name' => 'CSC 303'],
            ['id' => 23, 'name' => 'CSC 311'],
            ['id' => 24, 'name' => 'MAT 301'],
            ['id' => 25, 'name' => 'MAT 303'],
            ['id' => 26, 'name' => 'CSC 302'],
            ['id' => 27, 'name' => 'CSC 304'],
            ['id' => 28, 'name' => 'CSC 312'],
            ['id' => 29, 'name' => 'MAT 302'],
            ['id' => 30, 'name' => 'MAT 304'],
            ['id' => 31, 'name' => 'CSC 401'],
            ['id' => 32, 'name' => 'CSC 403'],
            ['id' => 33, 'name' => 'CSC 405'],
            ['id' => 34, 'name' => 'CSC 409'],
            ['id' => 35, 'name' => 'CSC 411'],
            ['id' => 36, 'name' => 'CSC 402'],
            ['id' => 37, 'name' => 'CSC 404'],
            ['id' => 38, 'name' => 'CSC 406'],
            ['id' => 39, 'name' => 'CSC 408'],
            ['id' => 40, 'name' => 'CSC 412'],
            ['id' => 41, 'name' => 'CSC 499'],
            ['id' => 42, 'name' => 'INF 102'],
            ['id' => 43, 'name' => 'INF 104'],
            ['id' => 44, 'name' => 'INF 110'],
            ['id' => 45, 'name' => 'INF 101'],
            ['id' => 46, 'name' => 'INF 103'],
            ['id' => 47, 'name' => 'INF 105'],
            ['id' => 48, 'name' => 'INF 201'],
            ['id' => 49, 'name' => 'INF 203'],
            ['id' => 50, 'name' => 'INF 205'],
            ['id' => 51, 'name' => 'INF 207'],
            ['id' => 52, 'name' => 'INF 209'],
            ['id' => 53, 'name' => 'INF 202'],
            ['id' => 54, 'name' => 'INF 204'],
            ['id' => 55, 'name' => 'INF 206'],
            ['id' => 56, 'name' => 'INF 208'],
            ['id' => 57, 'name' => 'INF 210'],
            ['id' => 58, 'name' => 'INF 301'],
            ['id' => 59, 'name' => 'INF 303'],
            ['id' => 60, 'name' => 'INF 305'],
            ['id' => 61, 'name' => 'INF 307'],
            ['id' => 62, 'name' => 'INF 309'],
            ['id' => 63, 'name' => 'INF 302'],
            ['id' => 64, 'name' => 'INF 304'],
            ['id' => 65, 'name' => 'INF 306'],
            ['id' => 66, 'name' => 'INF 308'],
            ['id' => 67, 'name' => 'INF 310'],
            ['id' => 68, 'name' => 'INF 401'],
            ['id' => 69, 'name' => 'INF 403'],
            ['id' => 70, 'name' => 'INF 405'],
            ['id' => 71, 'name' => 'INF 411'],
            ['id' => 72, 'name' => 'INF 413'],
            ['id' => 73, 'name' => 'INF 402'],
            ['id' => 74, 'name' => 'INF 404'],
            ['id' => 75, 'name' => 'INF 406'],
            ['id' => 76, 'name' => 'INF 408'],
            ['id' => 77, 'name' => 'INF 499'],
            ['id' => 78, 'name' => 'ECS 201'],
            ['id' => 79, 'name' => 'ECS 211'],
            ['id' => 80, 'name' => 'ECS 203'],
            ['id' => 81, 'name' => 'ECS 212'],
            ['id' => 82, 'name' => 'ECS 301'],
            ['id' => 83, 'name' => 'ECS 302'],
            ['id' => 84, 'name' => 'ECS 303']           
        ]);
    }
}
